services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-dev
      target: production
    env_file:
      - .env
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      PORT: ${PORT:-3000}
    restart: unless-stopped
