name: CI Image Scan

on:
  workflow_call:
    inputs:
      artifact-name:
        required: true
        type: string
      image-ref:
        required: true
        type: string

jobs:
  image-scan:
    name: Image Scan
    runs-on: ubuntu-latest
    steps:
      - name: Download image artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}

      - name: Load Docker image
        run: docker load -i ${{ inputs.artifact-name }}.tar

      - name: Scan image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ inputs.image-ref }}
          format: table
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: os,library
          severity: HIGH,CRITICAL
